Wed 11 14:24:14 [ERROR] Phalcon\Mvc\Model\Exception: Column 'batch_i' doesn't belong to any of the selected models (1), when preparing: SELECT [Image].* FROM [Image] WHERE batch_i = 1
File=C:\wamp64\www\gpap\app\models\Image.php
Line=100
#0 [internal function]: Phalcon\Mvc\Model\Query->_getQualified(Array)
#1 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array, true)
#2 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array)
#3 [internal function]: Phalcon\Mvc\Model\Query->_prepareSelect()
#4 [internal function]: Phalcon\Mvc\Model\Query->parse()
#5 [internal function]: Phalcon\Mvc\Model\Query->execute()
#6 C:\wamp64\www\gpap\app\models\Image.php(100): Phalcon\Mvc\Model::find(Array)
#7 C:\wamp64\www\gpap\app\controllers\ImageController.php(20): Image::find(Array)
#8 [internal function]: ImageController->listAction('1')
#9 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(ImageController), 'listAction', Array)
#10 [internal function]: Phalcon\Dispatcher->dispatch()
#11 C:\wamp64\www\gpap\public\index.php(42): Phalcon\Mvc\Application->handle()
#12 {main}

